#!/usr/bin/env python3
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("length", type=eval)  # forgive me father
    parser.add_argument("target", type=argparse.FileType("w"))
    args = parser.parse_args()

    args.target.write("w" * args.length)


if __name__ == "__main__":
    main()
