#!/usr/bin/env python3
# vim: tw=79
# Copyright © 2017 Endless Mobile, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
import argparse
import os
import subprocess
import tempfile


def cmd(*args):
    print('$', *args)
    subprocess.check_call(args)


def main():
    description = '''Sign 'file' using the given private key 'privkey'. The
    ASCII-armoured signature is written to 'file'.asc.'''

    epilog = '''We use a temporary directory in /tmp rather than in the
    builddir because GPG2 requires the use of gpg-agent and auto-launches
    it, communicating through a Unix socket in the GPG homedir. If the
    source/builddir are on a VirtualBox shared folder, this fails.

    Using a purely transient temporary directory also helps ensure this is
    isolated from the host system.'''
    p = argparse.ArgumentParser(description=description, epilog=epilog)
    p.add_argument('privkey', help='path to exported private key')
    p.add_argument('file', help='path to file to sign')
    a = p.parse_args()

    try:
        os.unlink(a.file + '.asc')
    except FileNotFoundError:
        pass

    with tempfile.TemporaryDirectory() as gnupghome:
        cmd("gpg", "--batch", "--homedir", gnupghome, "--import", a.privkey)
        cmd("gpg", "--batch", "--homedir", gnupghome, "--detach-sign",
            "--armor", a.file)
        cmd("gpgconf", "--homedir", gnupghome, "--kill", "gpg-agent")


if __name__ == '__main__':
    main()
