#!/bin/bash -e

# eos-test-mode - Setup system for non-persistent testing.
# Copyright (C) 2015  Dan Nicholson <nicholson@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# The /var/endless-extra SD card filesystem needs to be unmounted before
# adding the overlays below since the /var overlay will mask it.
extra_unit="var-endless\x2dextra.mount"
systemctl -q is-active "$extra_unit" && extra_active=true || extra_active=false

# Unmount the SD card
$extra_active && systemctl stop "$extra_unit"

# Mount overlays over any directory that might be written to
overlay_dirs="bin boot endless etc home lib opt ostree root sbin srv sysroot var"
for dir in $overlay_dirs; do
    [ -d /$dir ] || continue
    # If the directory is a symlink, assume it's pointing to a location
    # covered by another top level overlay
    [ -L /$dir ] && continue
    mkdir -p /run/eos-test/$dir /run/eos-test/$dir-workdir
    mount -t overlay -o \
        rw,upperdir=/run/eos-test/$dir,lowerdir=/$dir,workdir=/run/eos-test/$dir-workdir \
        eos-test-$dir /$dir
done

# Remount the SD card and mount a scratch overlay over it
if $extra_active; then
    systemctl start "$extra_unit"
    mkdir -p /run/eos-test/endless-extra /run/eos-test/endless-extra-workdir
    mount -t overlay -o \
        rw,upperdir=/run/eos-test/endless-extra,lowerdir=/var/endless-extra,workdir=/run/eos-test/endless-extra-workdir \
        eos-test-endless-extra /var/endless-extra
fi

# Disable the updater for this boot
systemctl stop eos-updater.timer
systemctl mask --runtime eos-updater.timer
