#!/bin/bash -e

# eos-test-mode - Setup system for non-persistent testing.
# Copyright (C) 2015  Dan Nicholson <nicholson@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Mount overlays over any directory that might be written to
overlay_dirs="boot etc home ostree root srv var"
for dir in $overlay_dirs; do
    [ -d /$dir ] || continue
    mkdir -p /run/eos-test/$dir
    mount -t overlayfs -o rw,upperdir=/run/eos-test/$dir,lowerdir=/$dir \
        eos-test-$dir /$dir
done

# Disable the updater for this boot
systemctl stop eos-updater.timer
systemctl mask --runtime eos-updater.timer
