#!/bin/sh

set -eu

# creating gnome-initial-setup user if it isn't already there
if ! getent passwd gnome-initial-setup >/dev/null; then
        adduser --system --force-badname --quiet \
            --home /run/gnome-initial-setup/ --no-create-home \
            --shell /bin/false \
            gnome-initial-setup
fi

# force our own session to run at first boot instead of the g-i-s
if [ ! -e /usr/share/gnome-session/sessions/gnome-initial-setup.session ] || \
      [ -L /usr/share/gnome-session/sessions/gnome-initial-setup.session ]; then
        cd /usr/share/gnome-session/sessions/
        ln -sf eos-installer.session gnome-initial-setup.session
fi


#DEBHELPER#

exit 0
