#!/bin/sh -e

if [ "$1" != upgrade ]; then
    # divert the gnome-initial-setup session
    dpkg-divert --package eos-installer --add --rename \
		--divert /usr/share/gnome-session/sessions/gnome-initial-setup.session.original \
		/usr/share/gnome-session/sessions/gnome-initial-setup.session
fi


