#!/bin/sh

set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    # Restore the original g-i-s session file
    dpkg-divert --package eos-installer --remove --rename \
    	--divert /usr/share/gnome-session/sessions/gnome-initial-setup.session.original \
		/usr/share/gnome-session/sessions/gnome-initial-setup.session
fi


#DEBHELPER#
exit 0
